baseURL = "https://moonlitusun.github.io/"
# title = "Hugo Themes"
author = "Roc"
copyright = "Copyright © 2017–2024, Steve Francia and the lee.so; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "gokarna"
title = "Moonlit"
staticDir = ['static']
pygmentsStyle = "onedark"

[params]
  tags = true
  color = 'linen'

  twitter = 'moonlitusun'
  github = 'moonlitusun'

  footer = "Roc"
  description = "窮且益堅，不墜青雲之志"
  AccentColor = "#8a2be2"

  avatarURL = 'https://moonlit.vip/images/avatar.jpg'
  ShowBackToTopButton = true
  name = 'Roc ☀️'

  socialIcons = [
    {name = "twitter", url = "https://twitter.com/roc_orange"},
    {name = "github", url = "https://github.com/moonlitusun"},
    {name = "email", url = "https://moonlitusun@gmail.com"},
  ]
  metaKeywords = ["moonlit", "roc", "roc sun"]

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  # giscus
[params.giscus]
  repo = 'moonlitusun/moonlitusun.github.io'                 # see https://giscus.app for more details
  repoId = 'MDEwOlJlcG9zaXRvcnkxODA3MDgxMzk='
  category = 'Announcements'
  categoryId = 'DIC_kwDOCsVjK84CcsCi'
  mapping = 'pathname'
  lang = 'en'
  [params.giscus.theme]
    light = 'light'
    dark = 'dark_dimmed'
    default = 'preferred_color_scheme'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[menu]
  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    pre = "<span data-feather='bookmark'></span>"
    name = "Tags"
    url = "/tags/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book-open'></span>"
    url = "/posts/"
    weight = 2
